"""
Comprehensive Chatbot Knowledge Base for Pushkarani System
"""

KNOWLEDGE_BASE = {
    'types': {
        'type-1': {
            'name': 'Teppakulam (Float Festival Tank)',
            'definition': 'A large, shallow temple tank designed for the Teppotsavam (float festival). It features a central pavilion (Maiya Mandapam) and spectator steps.',
            'characteristics': [
                'Central pavilion or island structure (Maiya Mandapam)',
                'Large, open water surface (typically shallow)',
                'Wide spectator steps around perimeter',
                'Festival-centric architecture',
                'Dimensions: typically 200m+ in length',
                'Allows boat processions during festivals',
                'Public participation oriented design'
            ],
            'example': 'Vandiyur Mariamman Teppakulam, Madurai (built 1645 CE)',
            'patronage': 'Nayaka Dynasty (16th-18th century)',
            'purpose': 'Ritual spectacle, float festivals, public engagement',
            'construction': 'Built by excavating earth and creating embankments. Walls reinforced with stone and mortar.',
            'maintenance': 'Requires regular de-silting and wall repairs. Spectator steps need attention.',
            'water_capacity': 'Can hold 10-50+ million liters depending on size',
            'history': 'The Vandiyur tank was created by excavating clay to make bricks for Thirumalai Nayak\'s palace',
            'significance': 'Symbol of secular space within temple - where common people gather for festivals',
            'dimensions_example': 'Vandiyur: approximately 240m x 240m',
            'famous_examples': [
                'Swami Pushkarini, Tirumala - Annual 5-day Teppotsavam with thousands of pilgrims',
                'Pushkar Lake, Rajasthan - Sacred pilgrimage site for all religions',
                'Golden Temple Pool, Amritsar - Center of Sikh spirituality',
                'Gokul Tank, Mathura - Associated with Lord Krishna traditions'
            ],
            'festival_traditions': 'During Teppotsavam, elaborately decorated boats carry temple deities around the tank while thousands watch from steps. The festival celebrates the deity\'s journey and blesses the community.',
            'engineering_feat': 'Built without modern machinery using gravity, channels, and manual labor over decades'
        },
        'type-2': {
            'name': 'Kalyani (Geometric Stepped Tank)',
            'definition': 'An ornate, subterranean stepped tank with complex geometric patterns. Open-air but featuring intricate pyramidal steps.',
            'characteristics': [
                'Complex, fractal-like step patterns',
                'Subterranean design (descends multiple levels)',
                'Symmetrical geometry and precision',
                'Dark stone construction (chlorite schist or granite)',
                'Engineering and aesthetic showcase',
                'Intricate carved decorations',
                'Multiple levels of steps (2-7 levels common)',
                'Narrow corridors and passages'
            ],
            'example': 'Stepped Tank in Hampi Royal Enclosure, Karnataka',
            'patronage': 'Vijayanagara Empire (14th-17th century)',
            'purpose': 'Royal ritual use, aesthetic expression, water management',
            'construction': 'Cut into rock or built with precisely fitted stone blocks. No mortar in some cases.',
            'depth': 'Can descend 20-40+ feet below ground level',
            'engineering': 'Sophisticated hydraulic systems with underground channels',
            'significance': 'Rani ki Vav in Patan, Gujarat is a UNESCO World Heritage site with 7 levels',
            'architecture': 'Combines functionality with artistic excellence',
            'location': 'Often built in royal palace complexes',
            'water_source': 'Connected to rivers or groundwater sources via underground channels',
            'famous_examples': [
                'Rani ki Vav, Patan - 11th century, 7 levels, 500+ sculptures, UNESCO World Heritage',
                'Chand Baori, Abhaneri - 10th century, 3500+ steps in geometric pattern',
                'Adalaj Vav, Ahmedabad - 15th century, 5 stories deep with intricate carvings',
                'Surya Kund, Ujjain - Ancient tank with 108 minor tanks around it'
            ],
            'artistic_value': 'Each step is carved with religious motifs, mythological scenes, and deity representations. Steps function as both stairs and art gallery.',
            'royal_significance': 'These tanks were status symbols for kingdoms, showcasing their wealth, engineering prowess, and architectural vision.',
            'modern_restoration': 'Many are being restored to original designs after centuries of modifications and damage'
        },
        'type-3': {
            'name': 'Kunda (Simple Rectangular Tank)',
            'definition': 'The foundational, multipurpose temple tank. A simple excavated basin with linear steps.',
            'characteristics': [
                'Simple, rectangular or square shape',
                'Linear stone steps (ghat)',
                'Functional design prioritizing utility',
                'Wide steps for community access',
                'Often decorated with colors or patterns',
                'Surface-level construction',
                'Multiple entry/exit points',
                'Open access design'
            ],
            'example': 'Haridra Nadhi, Mannargudi - 23 acres (largest in India)',
            'patronage': 'Pallava Dynasty (6th-9th century)',
            'purpose': 'Multi-purpose: ritual bathing, water storage, groundwater recharge, community gathering',
            'construction': 'Simple excavation with stone step cladding. Most economical design.',
            'water_capacity': 'Largest tanks can hold 100+ million liters',
            'community_use': 'Accessible to all community members without restrictions',
            'festivals': 'Hosts major festivals and pilgrimage gatherings',
            'maintenance': 'Requires de-silting and step maintenance',
            'significance': 'Foundation of Indian water management for over 2000 years',
            'sustainability': 'Supports groundwater recharge and long-term water security',
            'famous_examples': [
                'Haridra Nadhi, Mannargudi - 23 acres, largest temple tank in India',
                'Indrapratha Tank, Delhi - Ancient tank from Mahabharata era',
                'Rajarani Tank, Bhubaneswar - Associated with 11th century Rajarani Temple',
                'Kumara Dhara, Mysore - 16th century tank supplying water to entire city'
            ],
            'ecological_role': 'Supports aquatic life including rare fish species, birds, and aquatic plants. Connected to surrounding wetlands.',
            'seasonal_importance': 'During monsoon, captures 6+ months of water supply. Recharges wells in surrounding areas.',
            'agricultural_link': 'Many tanks supply irrigation water to farms, supporting local agriculture and food security',
            'community_traditions': 'Tanks host bathing festivals (Makar Sankranti), Diwali celebrations, and daily worship rituals'
        }
    },
    'general': {
        'what_is_pushkarani': 'A Pushkarani is a sacred temple pond or tank in India. It\'s not just a water body but a complex artifact of theology, ecology, engineering, and society. The term comes from Sanskrit, literally translating to "lotus pool". It\'s a repository of sacred water believed to have purifying and healing properties.',
        'history': 'The history of Pushkaranis spans over 2,000 years: (1) 3000 BCE - Great Bath of Mohenjo-Daro; (2) 6th-9th century - Pallava Dynasty created foundational designs; (3) 10th-13th century - Chola Dynasty perfected hydraulic engineering; (4) 14th-17th century - Vijayanagara Empire created masterpieces like Hampi tanks; (5) 16th-18th century - Nayaka Dynasty built iconic Teppakulams.',
        'engineering': 'Ancient builders used sophisticated hydraulic systems including: (1) Aqueducts and underground channels; (2) Lime mortar made from shell lime and clay minerals; (3) Stone structures that last centuries; (4) Water level management systems; (5) Multi-level step designs for durability; (6) Sluice gates and spillways for overflow management.',
        'vastu_shastra': 'According to Vastu Shastra, water bodies should be: (1) Located in North, Northeast, or East; (2) Deeper in the North; (3) Protected by natural features like hills; (4) Connected to auspicious directions; (5) Part of the temple\'s overall sacred geometry.',
        'purpose': 'Pushkaranis serve three main purposes: (1) Sacred purification - a place for ritual bathing and spiritual cleansing; (2) Water management - rainwater harvesting, storage, and groundwater recharge; (3) Social function - a community gathering space, venue for festivals, and symbol of shared resources.',
        'conservation': 'Over 100,000 Pushkaranis in India are not well maintained. Major issues: (1) Silting and water loss due to poor upkeep; (2) Urban encroachment and pollution; (3) Lack of government funding; (4) Absence of community involvement; (5) Damage from neglect and vandalism. Conservation is critical for water security.',
        'water_management': 'Traditional water management principles: (1) Rainwater harvesting during monsoons; (2) Recharging groundwater aquifers; (3) Supplying drinking and irrigation water; (4) Maintaining ecological balance; (5) Supporting agriculture in surrounding areas.',
        'contribute': 'You can contribute by: (1) Documenting tanks in your area with photos and measurements; (2) Participating in restoration projects with local organizations; (3) Raising awareness through social media and community engagement; (4) Supporting conservation NGOs financially or through volunteering; (5) Reporting damaged tanks to local authorities; (6) Educating family and community about importance.',
        'mythology': 'In Hindu tradition: (1) Sacred waters have purifying power; (2) Bathing in Pushkaranis washes away sins; (3) Each tank is associated with specific deities; (4) Pilgrimage to sacred tanks is a spiritual practice; (5) Water is considered "Tirtha" (sacred crossing point).',
        'climate_impact': 'In changing climate: (1) Tanks provide resilience against droughts; (2) Stored water sustains communities during water scarcity; (3) Recharging groundwater prevents wells from drying; (4) Proper maintenance becomes more critical than ever.',
        'architecture_style': 'Different dynasties developed distinct styles: (1) Pallava style - Simple, functional, community-focused; (2) Chola style - Grand, decorated, royal patronage; (3) Vijayanagara style - Complex geometry, precision engineering; (4) Nayaka style - Festival-oriented, theatrical design.',
        'famous_tanks': 'Notable Pushkaranis across India: Haridra Nadhi (Mannargudi) - 23 acres; Rani ki Vav (Patan) - 7 levels; Chand Baori (Abhaneri) - 3500+ steps; Swami Pushkarini (Tirumala) - annual festival; Golden Temple Pool (Amritsar) - Sikh sacred site; Pushkar Lake (Rajasthan) - pilgrimage center.',
        'restoration_projects': 'Modern efforts to restore Pushkaranis: Restoration has created local employment, involved communities, improved water security, and preserved cultural heritage. Programs teach youth about conservation and connect ancient wisdom with modern sustainability.',
        'spiritual_significance': 'Sacred bathing in Pushkaranis is believed to cleanse sins, grant blessings, and connect devotees with divine energy. Many tanks host annual pilgrimage events attracting millions. The spiritual power of tanks transcends religious boundaries.',
        'ecological_importance': 'Pushkaranis support biodiversity: aquatic plants, fish species, birds, and insects depend on them. They recharge groundwater, maintain local ecosystems, and support agriculture. Draining tanks threatens entire ecological networks.',
        'social_role': 'Historically and today, tanks serve as: Bathing and washing facilities; Community meeting places; Festival venues; Water distribution centers; Recreation areas; Symbol of shared community resources and social equality.',
        'construction_techniques': 'Traditional construction methods: (1) Site selection based on hydrology and Vastu; (2) Excavation using manpower and simple tools; (3) Stone quarrying and precision cutting; (4) Hydraulic lime mortar preparation; (5) Step construction with careful water management; (6) Sluice gate installation.',
        'water_conservation': 'Tanks are superior to dams for conservation: More surface area for evaporation but allows groundwater recharge; Distributed water management across region; Natural filtration through steps and channels; Flexible water sharing between communities; Less environmental disruption.',
        'tourist_destinations': 'Many Pushkaranis are major tourist attractions: Rani ki Vav in Gujarat - UNESCO site; Hampi tanks in Karnataka - archaeological wonder; Golden Temple in Punjab - religious pilgrimage; Pushkar Lake in Rajasthan - tourist destination; Meenakshi Temple tanks in Madurai - architectural marvel.',
    },
    'facts': [
        'The largest temple tank in India is the Haridra Nadhi in Mannargudi, Tamil Nadu, covering 23 acres (9.3 hectares).',
        'The Rani ki Vav in Patan, Gujarat is a UNESCO World Heritage site and descends 7 levels deep with 500+ sculptures.',
        'Over 100,000 Pushkaranis in India are not well maintained and face water loss.',
        'Ancient builders used hydraulic lime mortar made from shell lime and clay minerals that hardens underwater.',
        'The Hampi tanks were connected via a sophisticated network spanning miles to the Tungabhadra River.',
        'The Vandiyur Teppakulam in Madurai was created by excavating clay to make bricks for Thirumalai Nayak\'s palace.',
        'Pushkaranis were sometimes used to hide temple treasures during invasions by hostile forces.',
        'The Swami Pushkarini at Tirumala hosts an annual 5-day Teppotsavam festival with thousands of pilgrims.',
        'Vastu Shastra mandates that water bodies be located in the North, Northeast, or East of temple complexes.',
        'The term "Tirtha" refers both to a pilgrimage site and a sacred water body - they are inseparable in Hindu tradition.',
        'The Great Bath of Mohenjo-Daro (3000 BCE) is possibly the oldest known tank, predating temples by centuries.',
        'Pushkarani water is believed to have medicinal and healing properties in traditional Ayurvedic texts.',
        'Some tanks are connected to underground rivers that flow for miles without surfacing.',
        'Ancient tanks used silt traps to prevent silting - a design principle rediscovered by modern engineers.',
        'The Chola dynasty built hundreds of tanks across South India, many still functioning after 1000+ years.',
        'Temple tanks often have dedicated management structures with officers (Talaivar) in charge of maintenance.',
        'Pushkaranis support entire ecosystems with aquatic plants, fish, and bird species.',
        'The construction of a major Pushkarani sometimes took decades to complete.',
        'Some tanks have inscriptions in multiple languages, providing historical records.',
        'Monsoon water collection in tanks can sustain communities for 6+ months without rain.',
        'The design of steps in tanks considers water level fluctuations across seasons.',
        'Many tanks have underground chambers for water storage and cool areas for pilgrims.',
        'Sacred tanks are often fed by natural springs, adding to their spiritual significance.',
        'Tank maintenance required special skills in stone masonry and hydraulic engineering.',
        'Some Pushkaranis have temples built at the center on islands, creating unique architectural combinations.',
        'The reflection of temple architecture in tank waters is considered an important aesthetic element.',
        'Tank festivals attract millions of pilgrims and tourists annually.',
        'Biodiversity in temple tanks includes rare fish species and aquatic plants.',
        'Some tanks have been continuously maintained for 1500+ years without major reconstruction.',
        'The ancient concept of "Jalasrama" (tank network) connected multiple tanks for water sharing.',
        'Modern conservation efforts are bringing many abandoned tanks back to life.',
        'Tank water quality testing reveals natural filtration and purification processes.',
        'Some tanks have acoustic properties that create unique sound effects during ceremonies.',
        'Pushkarani restoration creates local employment and community engagement opportunities.',
        'Temple tank management traditionally involved complex water-sharing agreements between communities.',
        'Climate science confirms tanks are more effective than dams for groundwater recharge.',
        'Many tanks have saved communities during natural disasters by providing emergency water.',
        'Pushkarani education programs are being integrated into school curricula.',
        'Digital mapping of all Indian Pushkaranis is an ongoing conservation project.',
        'Some tanks are being restored to original designs after centuries of modifications.',
        'Tank restoration tourism is emerging as a new form of cultural and ecological tourism.',
        'Ancient tank builders had sophisticated understanding of hydrology and geology.',
        'Young volunteers are increasingly joining Pushkarani conservation efforts.',
        'Some tanks have become research sites for climate resilience and water security.',
        'Temple tank festivals contribute significantly to local economic development.',
        'Pushkarani conservation is recognized as critical for achieving UN Sustainable Development Goals.',
        'Some tanks demonstrate that human engineering can coexist with nature sustainably.',
        'The Pushkar Lake in Rajasthan attracts 2-3 million pilgrims annually for Pushkar Fair.',
        'Adalaj Vav in Ahmedabad took 15 years to construct and features 5 stories underground.',
        'Chand Baori has 3500 steps arranged in 13 tiers forming a geometric pattern visible from above.',
        'The Great Bath of Mohenjo-Daro (2500 BCE) measures 39ft x 23ft and was built with sophisticated waterproofing.',
        'Suraj Kund in Delhi was built in 10th century and is surrounded by 108 small tanks.',
        'The Indus Valley Civilization had at least 700 known tanks for water management.',
        'Meenakshi Temple tanks in Madurai were designed to align with cosmic and seasonal patterns.',
        'Chola dynasty king Rajendra I built over 200 tanks across South India in 11th century.',
        'Some Pushkaranis have connected channels that distribute water across 10+ kilometers.',
        'Tank water undergoes natural filtration through multiple layers of stone and sand.',
        'Ancient tanks used "fish farming" where controlled populations maintained water ecosystem balance.',
        'The Surya Kund temple tank in Ujjain has 108 associated minor tanks forming a sacred network.',
        'Tirupati Temple water tank capacity exceeds 50 million cubic feet serving pilgrims year-round.',
        'Some tanks have secret underground chambers used to hide temple valuables during invasions.',
        'The Viratnagar tank built in 8th century is still in use after 1200+ years.',
        'Tank festivals like Makar Sankranti bathing draws millions of pilgrims in single day.',
        'Kavi Kula Guru Kalidas wrote elaborate poetry describing temple tank beauty in 4th century.',
        'Tank inscriptions in Tamil, Sanskrit, Kannada, and Telugu provide historical narratives.',
        'Groundwater recharge from tanks can extend 100+ meters below tank surface.',
        'Some tanks maintain consistent temperature throughout year due to underground spring connections.',
        'The Khimnagar tank in Nashik is believed to be 1000 years old with intact original structure.',
        'Modern satellite mapping has identified 50,000+ temple tanks that need inventory and restoration.',
        'Tank-to-tank canal networks in South India span over 10,000 kilometers collectively.',
        'Narmada Valley tanks form the largest concentrated tank system in central India.',
        'Some tanks are mentioned in ancient texts like Brihat Samhita and Arthashastra as governance models.',
        'Pushkarani construction follows principles outlined in ancient architectural texts (Shilpashastra).',
        'Water quality in well-maintained tanks naturally achieves standards better than modern treatment.',
        'The step design allows water level adjustment without losing structural integrity.',
        'Seasonal monsoon water collection in tanks reduces requirement for wells by 70-80%.',
        'Tank management created ancient water bureaucracy with specialized officers and equitable distribution systems.',
        'Some tanks have hosted epic battles, royal ceremonies, and historical moments.',
        'Tank restoration projects have generated 50,000+ jobs in rural and urban areas.',
        'Pushkarani conservation attracts international researchers studying ancient water science.',
        'The carbon footprint of maintaining tanks is minimal compared to modern water infrastructure.',
        'Tank water supports aquatic biodiversity: fish, turtles, crabs, and rare plant species.',
        'Bird migrations follow tank systems with over 200 bird species using them as habitats.',
        'Tank renovation has revived species like Gharial crocodiles in certain regions.',
        'Some tanks have acoustic properties that create perfect amphitheater effects for celebrations.',
        'Tank festivals generate cultural tourism revenue of millions of rupees annually.'
    ],
    'keywords': {
        'teppakulam': 'type-1',
        'float festival': 'type-1',
        'festival tank': 'type-1',
        'swami pushkarini': 'type-1',
        'pushkar lake': 'type-1',
        'golden temple': 'type-1',
        'kalyani': 'type-2',
        'stepped tank': 'type-2',
        'rani ki vav': 'type-2',
        'chand baori': 'type-2',
        'adalaj vav': 'type-2',
        'hampi': 'type-2',
        'kunda': 'type-3',
        'simple tank': 'type-3',
        'rectangular tank': 'type-3',
        'haridra nadhi': 'type-3',
        'meenakshi': 'type-3',
        'conservation': 'conservation',
        'restoration': 'conservation',
        'water quality': 'water',
        'maintenance': 'maintenance',
        'history': 'history',
        'historical': 'history',
        'engineering': 'engineering',
        'architecture': 'engineering',
        'chola': 'history',
        'vijayanagara': 'history',
        'pallava': 'history',
        'nayaka': 'history',
        'mohenjo-daro': 'history',
        'ritual': 'general',
        'bathing': 'general',
        'pilgrimage': 'general',
        'spiritual': 'general',
        'biodiversity': 'general',
        'ecosystem': 'general',
        'drainage': 'general',
        'irrigation': 'general',
        'monsoon': 'general',
        'festival': 'general',
        'construction': 'engineering',
        'hydraulic': 'engineering',
        'aqueduct': 'engineering',
        'channels': 'engineering',
        'sluice': 'engineering',
        'drought': 'conservation',
        'climate': 'conservation',
        'tourism': 'conservation',
        'research': 'conservation'
    }
}
